
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ZcProjectManage
{

using System;
    using System.Collections.Generic;
    
public partial class Company
{

    public int id { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public string remark { get; set; }

    public string address { get; set; }

    public string connector { get; set; }

    public string connectnum { get; set; }

    public string connectorpos { get; set; }

    public Nullable<int> type { get; set; }

    public string modelids { get; set; }

    public string tagids { get; set; }

    public string officiaweb { get; set; }

}

}
