
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ZcProjectManage
{

using System;
    using System.Collections.Generic;
    
public partial class model
{

    public int id { get; set; }

    public string type { get; set; }

    public string uediitercontent { get; set; }

    public string typeids { get; set; }

    public string file { get; set; }

    public string remark { get; set; }

}

}
