
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ZcProjectManage
{

using System;
    using System.Collections.Generic;
    
public partial class project
{

    public int id { get; set; }

    public string name { get; set; }

    public Nullable<int> firstcompanyid { get; set; }

    public Nullable<int> secondcompanyid { get; set; }

    public Nullable<System.DateTime> createtime { get; set; }

    public Nullable<int> userid { get; set; }

    public string dockername { get; set; }

    public string typeids { get; set; }

    public string earlyfiles { get; set; }

    public string earlycontent { get; set; }

    public string solutionfiles { get; set; }

    public string solutioncontent { get; set; }

    public string finalfiles { get; set; }

    public string finalcontent { get; set; }

    public string remark { get; set; }

    public string holdutilname { get; set; }

    public string holdutilinfo { get; set; }

    public Nullable<int> state { get; set; }

}

}
